export const hiraTree = {
  "-": "ー",
  a: "あ",
  i: "い",
  u: "う",
  e: "え",
  o: "お",
  k: {
    a: "か",
    i: "き",
    u: "く",
    e: "け",
    o: "こ",
    y: {
      a: "きゃ",
      i: "きぃ",
      u: "きゅ",
      e: "きぇ",
      o: "きょ",
    },
    w: {
      a: "くぁ",
      i: "くぃ",
      u: "くぅ",
      e: "くぇ",
      o: "くぉ",
    },
  },
  s: {
    a: "さ",
    i: "し",
    u: "す",
    e: "せ",
    o: "そ",
    h: {
      a: "しゃ",
      i: "し",
      u: "しゅ",
      e: "しぇ",
      o: "しょ",
    },
    y: {
      a: "しゃ",
      i: "しぃ",
      u: "しゅ",
      e: "しぇ",
      o: "しょ",
    },
  },
  t: {
    a: "た",
    i: "ち",
    u: "つ",
    e: "て",
    o: "と",
    h: {
      a: "てゃ",
      i: "てぃ",
      u: "てゅ",
      e: "てぇ",
      o: "てょ",
    },
    y: {
      a: "ちゃ",
      i: "ちぃ",
      u: "ちゅ",
      e: "ちぇ",
      o: "ちょ",
    },
    s: {
      a: "つぁ",
      i: "つぃ",
      u: "つ",
      e: "つぇ",
      o: "つぉ",
    },
    w: {
      a: "とぁ",
      i: "とぃ",
      u: "とぅ",
      e: "とぇ",
      o: "とぉ",
    },
  },
  c: {
    a: "か",
    i: "し",
    u: "く",
    e: "せ",
    o: "こ",
    h: {
      a: "ちゃ",
      i: "ち",
      u: "ちゅ",
      e: "ちぇ",
      o: "ちょ",
    },
    y: {
      a: "ちゃ",
      i: "ちぃ",
      u: "ちゅ",
      e: "ちぇ",
      o: "ちょ",
    },
  },
  q: {
    a: "くぁ",
    i: "くぃ",
    u: "く",
    e: "くぇ",
    o: "くぉ",
  },
  n: {
    a: "な",
    i: "に",
    u: "ぬ",
    e: "ね",
    o: "の",
    n: "ん",
    y: {
      a: "にゃ",
      i: "にぃ",
      u: "にゅ",
      e: "にぇ",
      o: "にょ",
    },
  },
  h: {
    a: "は",
    i: "ひ",
    u: "ふ",
    e: "へ",
    o: "ほ",
    y: {
      a: "ひゃ",
      i: "ひぃ",
      u: "ひゅ",
      e: "ひぇ",
      o: "ひょ",
    },
    w: {
      a: "ふぁ",
      i: "ふぃ",
      e: "ふぇ",
      o: "ふぉ",
    },
  },
  f: {
    a: "ふぁ",
    i: "ふぃ",
    u: "ふ",
    e: "ふぇ",
    o: "ふぉ",
    y: {
      a: "ふゃ",
      u: "ふゅ",
      o: "ふょ",
    },
  },
  m: {
    a: "ま",
    i: "み",
    u: "む",
    e: "め",
    o: "も",
    y: {
      a: "みゃ",
      i: "みぃ",
      u: "みゅ",
      e: "みぇ",
      o: "みょ",
    },
  },
  y: {
    a: "や",
    u: "ゆ",
    e: "いぇ",
    o: "よ",
  },
  r: {
    a: "ら",
    i: "り",
    u: "る",
    e: "れ",
    o: "ろ",
    y: {
      a: "りゃ",
      i: "りぃ",
      u: "りゅ",
      e: "りぇ",
      o: "りょ",
    },
  },
  w: {
    a: "わ",
    i: "うぃ",
    u: "う",
    e: "うぇ",
    o: "を",
    h: {
      a: "うぁ",
      i: "うぃ",
      u: "う",
      e: "うぇ",
      o: "うぉ",
    },
    y: {
      i: "ゐ",
      e: "ゑ",
    },
  },
  g: {
    a: "が",
    i: "ぎ",
    u: "ぐ",
    e: "げ",
    o: "ご",
    y: {
      a: "ぎゃ",
      i: "ぎぃ",
      u: "ぎゅ",
      e: "ぎぇ",
      o: "ぎょ",
    },
    w: {
      a: "ぐぁ",
      i: "ぐぃ",
      u: "ぐぅ",
      e: "ぐぇ",
      o: "ぐぉ",
    },
  },
  z: {
    a: "ざ",
    i: "じ",
    u: "ず",
    e: "ぜ",
    o: "ぞ",
    y: {
      a: "じゃ",
      i: "じぃ",
      u: "じゅ",
      e: "じぇ",
      o: "じょ",
    },
  },
  j: {
    a: "じゃ",
    i: "じ",
    u: "じゅ",
    e: "じぇ",
    o: "じょ",
    y: {
      a: "じゃ",
      i: "じぃ",
      u: "じゅ",
      e: "じぇ",
      o: "じょ",
    },
  },
  d: {
    a: "だ",
    i: "ぢ",
    u: "づ",
    e: "で",
    o: "ど",
    h: {
      a: "でゃ",
      i: "でぃ",
      u: "でゅ",
      e: "でぇ",
      o: "でょ",
    },
    y: {
      a: "ぢゃ",
      i: "ぢぃ",
      u: "ぢゅ",
      e: "ぢぇ",
      o: "ぢょ",
    },
    w: {
      a: "どぁ",
      i: "どぃ",
      u: "どぅ",
      e: "どぇ",
      o: "どぉ",
    },
  },
  b: {
    a: "ば",
    i: "び",
    u: "ぶ",
    e: "べ",
    o: "ぼ",
    y: {
      a: "びゃ",
      i: "びぃ",
      u: "びゅ",
      e: "びぇ",
      o: "びょ",
    },
  },
  v: {
    a: "ゔぁ",
    i: "ゔぃ",
    u: "ゔ",
    e: "ゔぇ",
    o: "ゔぉ",
    y: {
      a: "ゔゃ",
      i: "ゔぃ",
      u: "ゔゅ",
      e: "ゔぇ",
      o: "ゔょ",
    },
  },
  p: {
    a: "ぱ",
    i: "ぴ",
    u: "ぷ",
    e: "ぺ",
    o: "ぽ",
    y: {
      a: "ぴゃ",
      i: "ぴぃ",
      u: "ぴゅ",
      e: "ぴぇ",
      o: "ぴょ",
    },
  },
  x: {
    a: "ぁ",
    i: "ぃ",
    u: "ぅ",
    e: "ぇ",
    o: "ぉ",
    y: {
      a: "ゃ",
      i: "ぃ",
      u: "ゅ",
      e: "ぇ",
      o: "ょ",
    },
    t: {
      u: "っ",
      s: {
        u: "っ",
      },
    },
    w: {
      a: "ゎ",
    },
    n: "ん",
    k: {
      a: "ゕ", // 実際には "ヵ" になる
      e: "ゖ", // 実際には "ヶ" になる
    },
  },
  l: {
    a: "ぁ",
    i: "ぃ",
    u: "ぅ",
    e: "ぇ",
    o: "ぉ",
    y: {
      a: "ゃ",
      i: "ぃ",
      u: "ゅ",
      e: "ぇ",
      o: "ょ",
    },
    t: {
      u: "っ",
      s: {
        u: "っ",
      },
    },
    w: {
      a: "ゎ",
    },
    k: {
      a: "ゕ", // 実際には "ヵ" になる
      e: "ゖ", // 実際には "ヶ" になる
    },
  },
};

export const romanMap = {
    あ: "a",
    い: "i",
    う: "u",
    え: "e",
    お: "o",
    か: "ka",
    き: "ki",
    く: "ku",
    け: "ke",
    こ: "ko",
    さ: "sa",
    し: { hepburn: "shi", kunrei: "si" },
    す: "su",
    せ: "se",
    そ: "so",
    た: "ta",
    ち: { hepburn: "chi", kunrei: "ti" },
    つ: { hepburn: "tsu", kunrei: "tu" },
    て: "te",
    と: "to",
    な: "na",
    に: "ni",
    ぬ: "nu",
    ね: "ne",
    の: "no",
    は: "ha",
    ひ: "hi",
    ふ: { hepburn: "fu", kunrei: "hu" },
    へ: "he",
    ほ: "ho",
    ま: "ma",
    み: "mi",
    む: "mu",
    め: "me",
    も: "mo",
    や: "ya",
    ゆ: "yu",
    よ: "yo",
    ら: "ra",
    り: "ri",
    る: "ru",
    れ: "re",
    ろ: "ro",
    わ: "wa",
    ゐ: "wi",
    ゑ: "we",
    を: { hepburn: "o", kunrei: "wo" },
    ん: "n",
    が: "ga",
    ぎ: "gi",
    ぐ: "gu",
    げ: "ge",
    ご: "go",
    ざ: "za",
    じ: { hepburn: "ji", kunrei: "zi" },
    ず: "zu",
    ぜ: "ze",
    ぞ: "zo",
    だ: "da",
    ぢ: { hepburn: "ji", kunrei: "di" },
    づ: { hepburn: "zu", kunrei: "du" },
    で: "de",
    ど: "do",
    ば: "ba",
    び: "bi",
    ぶ: "bu",
    べ: "be",
    ぼ: "bo",
    ぱ: "pa",
    ぴ: "pi",
    ぷ: "pu",
    ぺ: "pe",
    ぽ: "po",
    きゃ: "kya",
    きぃ: "kyi",
    きゅ: "kyu",
    きぇ: "kye",
    きょ: "kyo",
    くぁ: "qa",
    くぃ: "qi",
    くぇ: "qe",
    くぉ: "qo",
    くゃ: "qya",
    くゅ: "qyu",
    くょ: "qyo",
    しゃ: { hepburn: "sha", kunrei: "sya" },
    しぃ: "syi",
    しゅ: { hepburn: "shu", kunrei: "syu" },
    しぇ: "sye",
    しょ: { hepburn: "sho", kunrei: "syo" },
    ちゃ: { hepburn: "cha", kunrei: "tya" },
    ちぃ: { hepburn: "chi", kunrei: "tyi" },
    ちゅ: { hepburn: "chu", kunrei: "tyu" },
    ちぇ: { hepburn: "che", kunrei: "tye" },
    ちょ: { hepburn: "cho", kunrei: "tyo" },
    てゃ: "tha",
    てぃ: "thi",
    てゅ: "thu",
    てぇ: "the",
    てょ: "tho",
    ひゃ: "hya",
    ひゅ: "hyu",
    ひぇ: "hye",
    ひょ: "hyo",
    ふぁ: "fa",
    ふぃ: "fi",
    ふぇ: "fe",
    ふぉ: "fo",
    みゃ: "mya",
    みゅ: "myu",
    みぇ: "mye",
    みょ: "myo",
    ヴぁ: "va",
    ヴぃ: "vi",
    ヴぇ: "ve",
    ヴぉ: "vo",
    ぎゃ: "gya",
    ぎゅ: "gyu",
    ぎぇ: "gye",
    ぎょ: "gyo",
    じゃ: { hepburn: "ja", kunrei: "zya" },
    じゅ: { hepburn: "ju", kunrei: "zyu" },
    じぇ: "zye",
    じょ: { hepburn: "jo", kunrei: "zyo" },
    ぢゃ: { hepburn: "dya", kunrei: "zya" },
    ぢゅ: { hepburn: "dyu", kunrei: "zya" },
    ぢぇ: "dye",
    ぢょ: { hepburn: "dyo", kunrei: "zya" },
    びゃ: "bya",
    びゅ: "byu",
    びぇ: "bye",
    びょ: "byo",
    ぴゃ: "pya",
    ぴゅ: "pyu",
    ぴぇ: "pye",
    ぴょ: "pyo",
    りゃ: "rya",
    りゅ: "ryu",
    りぇ: "rye",
    りょ: "ryo",
    にゃ: "nya",
    にゅ: "nyu",
    にぇ: "nye",
    にょ: "nyo",
    ゔ: "bu",
    "、": ",",
    "，": ",",
    "。": ".",
    ー: "-",
    "〜": "~",
    "＿": "_",
    "＝": "=",
    "？": "?",
    "！": "!",
    "（": "(",
    "）": ")",
    "「": "[",
    "」": "]",
    "＜": "<",
    "＞": ">",
    "＃": "#",
    "＄": "$",
    "％": "%",
    "＆": "&",
    "＾": "^",
    "＊": "*",
    "＋": "+",
    "＠": "@",
    "：": ":",
    "；": ";",
    "／": "/",
    "・": "/",
    "’": "'",
    "”": '"',
    "￥": "\\",
    "｜": "|",
    "１": "1",
    "２": "2",
    "３": "3",
    "４": "4",
    "５": "5",
    "６": "6",
    "７": "7",
    "８": "8",
    "９": "9",
    "０": "0",
    ぁ: "a",
    ぃ: "i",
    ぅ: "u",
    ぇ: "e",
    ぉ: "o",
  };

export function romaToHira(roma) {
  let result = "";
  let tmp = "";
  let index = 0;
  let node = tree;
  const len = roma.length;

  const push = (char, toRoot = true) => {
    result += char;
    tmp = "";
    node = toRoot ? tree : node;
  };

  while (index < len) {
    const char = roma.charAt(index);
    if (char.match(/[a-z-]/)) {
      if (char in node) {
        const next = node[char];
        if (typeof next === "string") {
          push(next);
        } else {
          tmp += roma.charAt(index);
          node = next;
        }
        index++;
        continue;
      }
      const prev = roma.charAt(index - 1);
      if (prev && (prev === "n" || prev === char)) {
        push(prev === "n" ? "ん" : "っ", false);
      }
      if (node !== tree && char in tree) {
        push(tmp);
        continue;
      }
    }
    push(tmp + char);
    index++;
  }
  tmp = tmp.replace(/n$/, "ん");
  push(tmp);
  return result;
}
